name: jaguar_session_mongo
description: MongoDb based session manager for Jaguar.dart. Stores session data in a MongoDb collection.
version: 2.4.1
homepage: https://github.com/Jaguar-dart/session
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  mongo_dart: ^0.3.2
  jaguar: ^2.4.0
  jaguar_serializer: ^2.2.0
  jaguar_data_store: ^2.2.0
  jaguar_mongo_data_store: ^2.1.1
  crypto: ^2.0.1

dev_dependencies:
  test: ^1.3.0
  jaguar_auth: ^2.4.0
  jaguar_resty: ^2.6.6
  jaguar_reflect: ^2.4.0
  jaguar_mongo: ^2.2.0
  jaguar_example_session_models:
    path: ../example_models
  http:
